### ISSUE TITLE
Get the voice data

### ISSUE THREAD

**Issue by elpaxdota** [PerfectLaugh/VoiceTools#1]
Hello I found your great extension. There is compress/decompress and send voice to client functions. But can you explain me how to get the voice data ? Because old method with detour seems not working now. And you have only extension on github (and maybe internet) that working with "new" csgo celt codec. Thanks.

**Comment by PerfectLaugh** [comment]
If you want to get the voice data, then you have to hook the SendNetMsg function.
I think this can be done by SourceHook in theory, but I dont sure, since I have never done this.

**Comment by PerfectLaugh** [comment]
What do you want to get the voice data by the way?

**Comment by elpaxdota** [comment]
I don't know. Maybe some transmission to the web.

**Comment by PerfectLaugh** [comment]
I want to help you, but I'm afraid I don't have time. I can't provide any support about this extension.
Please note that this extension is just a reference implementation. No guarantee of whether it is working (Since I'm out of maintaining this project)
But please feel free to ask any question by opening issue. I will try to help you as much as possible.
